version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: increase_versions

    commit_message:
      prefix: "fix"
      include_scope: true

    allowed_updates:
      - match:
          dependency_name: "@stoplight/*" # match all Stoplight deps, regardless of type
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "all"
      - match:
          dependency_type: "development"
          update_type: "security"

  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly" # we do not need to check for devDependencies updates on a daily basis
    version_requirement_updates: increase_versions

    commit_message:
      prefix: "chore"
      include_scope: true

    allowed_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
